on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runtime: win-x64
            platform: x64
          - runtime: win-x64
            platform: x64
            self-contained: true
          - runtime: win-arm64
            platform: arm64
          - runtime: win-arm64
            platform: arm64
            self-contained: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet publish src/AutoUpdate/AutoUpdate.csproj -o bin/lipui -r ${{ matrix.runtime }}

      - if: !matrix.self-contained
        run: |
          dotnet publish src/LipUI/LipUI.csproj -o bin/lipui -r ${{ matrix.runtime }} `
          -p:DebugType=none -p:Platform=${{ matrix.platform }}

      - if: matrix.self-contained
        run: |
          dotnet publish src/LipUI/LipUI.csproj -o bin/lipui -r ${{ matrix.runtime }} `
          -p:DebugType=none -p:Platform=${{ matrix.platform }} `
          --self-contained -p:WindowsAppSDKSelfContained=true

      - run: |
          copy runtimes/win10-${{ matrix.platform }}/native/Microsoft.WindowsAppRuntime.Bootstrap.dll bin/lipui

      - uses: actions/upload-artifact@v4
        with:
          name: LipUI-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

  check-style:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet format --verify-no-changes src/LipUI
