name: Build CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Install the .NET 7 workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build with .NET Framework
      run: dotnet publish --framework net462 -c Release -o bin\default src\LipUI\LipUI.csproj
    - name: Upload LipUI.exe
      uses: actions/upload-artifact@v2
      with:
        name: LipUI.exe
        path: bin/default/LipUI.exe
    - name: Build with .NET 7
      run: dotnet publish --framework net7.0-windows -c Release -o bin\dotnet7 src\LipUI\LipUI.csproj
    - name: Upload LipUI dotnet7
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/dotnet7
        


